ActiveSupport::CoreExtensions::Date::Conversions::DATE_FORMATS[:number_date] = '%m-%d-%y'
ActiveSupport::CoreExtensions::Date::Conversions::DATE_FORMATS[:sales_date] = '%m-%d-%y'
ActiveSupport::CoreExtensions::Date::Conversions::DATE_FORMATS[:purchase_date] = '%m-%d-%y'
ActiveSupport::CoreExtensions::Date::Conversions::DATE_FORMATS[:day_month_year] = '%d-%m-%y'
ActiveSupport::CoreExtensions::Date::Conversions::DATE_FORMATS[:shipper_date] = '%m-%d-%y'
ActiveSupport::CoreExtensions::Date::Conversions::DATE_FORMATS[:backorder_date] = '%m/%d/%y'

ActiveSupport::CoreExtensions::Time::Conversions::DATE_FORMATS[:number_date] = '%m-%d-%y'
ActiveSupport::CoreExtensions::Time::Conversions::DATE_FORMATS[:sales_date] = '%m-%d-%y'
ActiveSupport::CoreExtensions::Time::Conversions::DATE_FORMATS[:purchase_date] = '%m-%d-%y'
ActiveSupport::CoreExtensions::Time::Conversions::DATE_FORMATS[:number_date_time] = '%m-%d-%Y %I:%M %p'
ActiveSupport::CoreExtensions::Time::Conversions::DATE_FORMATS[:time] = '%I:%M %p'
ActiveSupport::CoreExtensions::Time::Conversions::DATE_FORMATS[:event_date] = '%b %d, %Y'
ActiveSupport::CoreExtensions::Time::Conversions::DATE_FORMATS[:day_month_year] = '%d-%m-%y'
ActiveSupport::CoreExtensions::Time::Conversions::DATE_FORMATS[:shipper_date] = '%m-%d-%y'
ActiveSupport::CoreExtensions::Time::Conversions::DATE_FORMATS[:backorder_date] = '%m/%d/%y'
